spring:
  datasource:
    username: root
    password: Windows8
    url: jdbc:mysql://47.94.192.199:3306/skydb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
